### ISSUE TITLE
Load from folder

### ISSUE THREAD

**Issue by ghost** [gsaurus/pluma#1]
I can load plugins from a specific folder
I can also load plugins with their specific filename

I cannot load plugins from the directories "", ".", "./", "/"
Please can you fix this, I've noticed that you've heard of this before and have not done anything about it. I cannot find the problem with your code.

I'm using Windows

Thanks
- BoorishPea

**Comment by gsaurus** [comment]
I wasn't aware of this problem. Apparently it only happens for certain versions of Windows. For instance, I couldn't reproduce on Windows XP.
Applied a fix in Dir.cpp.

Use "" to load plugins from current directory.
